"""empty message

Revision ID: 1b89f94dc7cd
Revises: 5f56433d0dc1
Create Date: 2017-01-03 20:56:00.608000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b89f94dc7cd'
down_revision = '5f56433d0dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_articles_pub_time'), 'articles', ['pub_time'], unique=False)
    op.create_index(op.f('ix_messages_pub_time'), 'messages', ['pub_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_pub_time'), table_name='messages')
    op.drop_index(op.f('ix_articles_pub_time'), table_name='articles')
    # ### end Alembic commands ###
