"""empty message

Revision ID: 2487f672245c
Revises: 755bef50410f
Create Date: 2017-03-07 16:12:45.012000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2487f672245c'
down_revision = '755bef50410f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('about_md', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'about_md')
    # ### end Alembic commands ###
