"""empty message

Revision ID: 78b859a7c439
Revises: 1b89f94dc7cd
Create Date: 2017-01-04 18:15:44.140000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b859a7c439'
down_revision = '1b89f94dc7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('body_md', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'body_md')
    # ### end Alembic commands ###
