"""empty message

Revision ID: 7f5c9e993be1
Revises: 2979155a1db6
Create Date: 2017-02-15 15:40:45.949000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5c9e993be1'
down_revision = '2979155a1db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_browser', sa.String(length=20), nullable=True))
    op.add_column('comments', sa.Column('user_ip', sa.String(length=20), nullable=True))
    op.add_column('comments', sa.Column('user_platform', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'user_platform')
    op.drop_column('comments', 'user_ip')
    op.drop_column('comments', 'user_browser')
    # ### end Alembic commands ###
