"""empty message

Revision ID: a99410dd19b7
Revises: d8d1b418f41c
Create Date: 2017-02-16 18:30:55.662000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a99410dd19b7'
down_revision = 'd8d1b418f41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'gender',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)
    op.alter_column('profiles', 'nickname',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'nickname',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('profiles', 'gender',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)
    # ### end Alembic commands ###
